name: cd

on:
  push:
    branches:
      - develop
jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            if [ -d "${{ secrets.DIRECTORY }}" ]; then
                echo "Directory exists, pulling from repo";
                cd "${{ secrets.DIRECTORY }}";
                git pull origin develop;
            else
                echo "Directory does not exist, cloning repo";
                git clone "https://github.com/${{ github.repository }}" "${{ secrets.DIRECTORY }}";
                cd "${{ secrets.DIRECTORY }}";
            fi
            echo "Installing dependencies";
            docker pull ${{vars.REPOSITORY}}:${{ env.GITHUB_PR_NUMBER }};
            docker run -d -p ${{secrets.EXPORT_PORT}}:${{secrets.CONTAINER_PORT}} --env-file .env ${{vars.REPOSITORY}}:${{ env.GITHUB_PR_NUMBER }};
