name: cd

on:
  push:
    branches:
      - develop
env:
  GITHUB_COMMIT_ID: ${{github.event.commit_comment.comment.id}}
jobs:
  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{vars.REPOSITORY}}:${{ env.GITHUB_COMMIT_ID }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            if [ -d "${{ secrets.DIRECTORY }}" ]; then
                echo "Directory exists, pulling from repo";
                cd "${{ secrets.DIRECTORY }}";
                git pull origin develop;
            else
                echo "Directory does not exist, cloning repo";
                git clone "https://github.com/${{ github.repository }}" "${{ secrets.DIRECTORY }}";
                cd "${{ secrets.DIRECTORY }}";
            fi
            echo "Installing dependencies";
            docker pull ${{vars.REPOSITORY}};
            docker run -d -p ${{secrets.EXPORT_PORT}}:${{secrets.CONTAINER_PORT}} --env-file .env ${{vars.REPOSITORY}};
